### PR TITLE
replaced spec with overview page

### PR DESCRIPTION
**Pull request by bergos**
This replaces the spec as the start page with an overview page. It contains links to the specifications ins JSON-LD. The embedded JSON-LD and some very simple Vue code is used to render the HTML. Bootstrap is used for the layout. It's also already prepared to add documentations and libraries. I focused on:

- very simple and pragmatic content, HTML and JS
  - which should allow visitors to find fast what they are looking for
  - also it doesn't require special knowledge in any framework to make PR
- A little bit of dogfooding by having a semantic description of the content

Proposals for text changes a very welcome. Discussion about what belongs to the documentations and libraries section should go into a separate issue/PR.

### CODE REVIEW

**Review by elf-pavlik — APPROVED** [review]
great start, thanks @bergos !

**Comment by vhf** [comment]
I think it would be a bit better for SEO to have static HTML content instead of client-side generation based on the ld+json present in the HTML?

**Comment by RubenVerborgh** [comment]
> client-side generation based on the ld+json

Google looks at your site in a headless browser and gives it a couple of seconds to execute, I have been told by @danbri.

**Comment by elf-pavlik** [comment]
I think we should merge it ASAP and then we can always create issues to discuss changes and follow up on them with PRs. Any more approving reviews?

**Comment by danbri** [comment]
you should be able to see that in
https://developers.google.com/structured-data/testing-tool/

**Review by rubensworks — APPROVED** [review]
Looks good!

I would suggest having a short description on this page explaining what RDFJS is exactly, and its purpose. But perhaps this is something for a follow-up PR.

**Review by l00mi — APPROVED** [review]
@bergos Looks very good IMHO. What I don't get, do you have the specs also ready to put in the linked too places? Or do I miss something?

Once we have the specs also available lets merge.

**Comment by elf-pavlik** [comment]
I have extracted: https://rdf.js.org/stream-spec/
And renamed `representation-task-force` repo to `data-model-spec`
Everything should work now

**Pull request merged**
